import urlManifest from '../../media-manifest.json'
import type { Work } from '../../lib/gallery-curation'

// Re-exported so existing imports (`import { type Work } from './content'`) keep working.
export type { Work, HeroTile } from '../../lib/gallery-curation'

/* ----------------------------------------------------------------------------
   Flux Ads — site content
   Edit copy here, or swap the showcase placeholders for real media `src`s.
---------------------------------------------------------------------------- */

/* WhatsApp — "Text us" buttons open a chat to this number with a prefilled note.
   Number: +233 53 265 1684 (digits only, no + or spaces, for the wa.me link). */
const WHATSAPP_NUMBER = '233532651684'
const WHATSAPP_MESSAGE =
  "Hi Flux Ads! 👋 I'd like to create some AI ad content. Here's what I have in mind:"

export const WHATSAPP_DISPLAY = '+233 53 265 1684'
export const WHATSAPP_LINK = `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(
  WHATSAPP_MESSAGE,
)}`
export const TIKTOK_LINK =
  'https://www.tiktok.com/@fluxads.fx?_r=1&_t=ZS-97ESxNxiXI4'

export type Service = {
  no: string
  title: string
  blurb: string
}

export const services: Service[] = [
  {
    no: '01',
    title: 'AI Product Imagery',
    blurb:
      'Studio-grade product shots generated from a single reference — every angle, surface and light setup, no studio booking required.',
  },
  {
    no: '02',
    title: 'AI Video & Motion Ads',
    blurb:
      'Scroll-stopping motion spots for social and web. Hero loops, product reveals and lifestyle scenes rendered in any aspect ratio.',
  },
  {
    no: '03',
    title: 'Image Restoration',
    blurb:
      'Old, low-res or damaged shots rebuilt to crisp, modern, campaign-ready quality — colour, detail and resolution restored.',
  },
  {
    no: '04',
    title: 'Creative Direction',
    blurb:
      'Concept, styling and art direction tuned to your brand so every frame feels intentional — not generic AI output.',
  },
]

export type Category = {
  label: string
  copy: string
}

export const categories: Category[] = [
  {
    label: 'Product Photography',
    copy: 'Clean, dramatic or editorial — packshots and hero stills that sell.',
  },
  {
    label: 'Food & Beverage',
    copy: 'Mouth-watering, true-to-life food and drink visuals for menus and ads.',
  },
  {
    label: 'E-Commerce',
    copy: 'On-model, on-white and lifestyle sets built for catalogue scale.',
  },
  {
    label: 'Beauty & Fashion',
    copy: 'Skin, fabric and texture rendered with luxury-campaign polish.',
  },
  {
    label: 'Advertising',
    copy: 'Full creative concepts — stills and motion — built to convert.',
  },
]

/* ----------------------------------------------------------------------------
   Gallery — real Flux Ads work, hosted on Vercel Blob (CDN).
   src/media-manifest.json maps each filename to its public CDN URL and is
   regenerated by `node scripts/upload-blob.mjs`. To add new work: drop the
   original into src/assets/gallery/, re-run the optimize + upload scripts, then
   add an entry to `works` below referencing the original filename.
---------------------------------------------------------------------------- */
const manifest = urlManifest as Record<string, string>

/** Resolve a filename to its hosted CDN URL. Empty until the upload script runs. */
const m = (file: string): string => {
  const url = manifest[file]
  if (!url && import.meta.env.DEV) {
    console.warn(`[flux] media not uploaded: "${file}" — run: node scripts/upload-blob.mjs`)
  }
  return url ?? ''
}

/* The list below is now a *fallback snapshot* only. The live gallery is served
   by GET /api/gallery (which lists Vercel Blob) and consumed via useGallery();
   this array renders instantly on first paint and if that request fails. */
export const works: Work[] = [
  {
    id: 'w01',
    title: 'Mother & Child — Cinematic',
    category: 'Advertising',
    type: 'image',
    aspect: 'aspect-[9/16]',
    src: m('A_cinematic_4K_vertical_9_16_202605051608.jpeg'),
  },
  {
    id: 'w02',
    title: 'Studio Beauty Portrait',
    category: 'Beauty',
    type: 'image',
    aspect: 'aspect-[3/4]',
    src: m('04afa4de-9b0c-4e30-97c8-f1f1f5fee9b6.JPG'),
  },
  {
    id: 'w03',
    title: 'Wrap Dress — Motion Try-On',
    category: 'Fashion',
    type: 'video',
    aspect: 'aspect-[9/16]',
    src: m('doc_2026-06-15_13-45-51.mp4'),
  },
  {
    id: 'w19',
    title: 'Menswear — Studio Portrait',
    category: 'Fashion',
    type: 'image',
    aspect: 'aspect-[4/5]',
    src: m('menswear-portrait.jpeg'),
  },
  {
    id: 'w04',
    title: 'Laundry Capsules — Product Ad',
    category: 'Product',
    type: 'image',
    aspect: 'aspect-[9/16]',
    src: m('81c65654-d7aa-4e88-8de8-9ca45eb3b814.JPG'),
  },
  {
    id: 'w05',
    title: 'Skincare — Premium Still',
    category: 'Beauty',
    type: 'image',
    aspect: 'aspect-[9/16]',
    src: m('A_premium_4K_vertical_9_16_202605051519 (2).jpeg'),
  },
  {
    id: 'w06',
    title: 'Court Side — Sport Editorial',
    category: 'Fashion',
    type: 'image',
    aspect: 'aspect-[9/16]',
    src: m('freepik_use_the_uploaded_image_as_referencetransform_the_s_15439.jpeg'),
  },
  {
    id: 'w20',
    title: 'Coastal Linen — Motion',
    category: 'Fashion',
    type: 'video',
    aspect: 'aspect-[9/16]',
    src: m('menswear-coastal-linen.mp4'),
  },
  {
    id: 'w26',
    title: 'Profile — Cinematic Light',
    category: 'Fashion',
    type: 'image',
    aspect: 'aspect-[9/16]',
    src: m('menswear-profile.jpeg'),
  },
  {
    id: 'w21',
    title: 'Beach Walk — Editorial',
    category: 'Fashion',
    type: 'video',
    aspect: 'aspect-[9/16]',
    src: m('menswear-beach-walk.mp4'),
  },
  {
    id: 'w07',
    title: 'Cookie Crumbles — Food Ad',
    category: 'Food & Beverage',
    type: 'image',
    aspect: 'aspect-[3/4]',
    src: m('rEMOVE_cookies_by_crumbel_text_202605052153.jpeg'),
  },
  {
    id: 'w08',
    title: 'Celebration — Beverage Ad',
    category: 'Advertising',
    type: 'image',
    aspect: 'aspect-[9/16]',
    src: m('47c3ebf5-879b-494a-b354-82ba1f0b7dd2.JPG'),
  },
  {
    id: 'w09',
    title: 'Clean & Fresh — Campaign',
    category: 'Product',
    type: 'image',
    aspect: 'aspect-[9/16]',
    src: m('37fba723-4279-48c7-89bd-19d88e3f73fe.JPG'),
  },
  {
    id: 'w10',
    title: 'Coastal — Menswear',
    category: 'Fashion',
    type: 'image',
    aspect: 'aspect-square',
    src: m('f131c548-b327-42bb-9003-03544d3677cb.JPG'),
  },
  {
    id: 'w22',
    title: 'Knitwear — Orbit Shot',
    category: 'Fashion',
    type: 'video',
    aspect: 'aspect-[9/16]',
    src: m('menswear-knitwear-orbit.mp4'),
  },
  {
    id: 'w27',
    title: 'Knit Texture — Close-Up',
    category: 'Fashion',
    type: 'image',
    aspect: 'aspect-[9/16]',
    src: m('menswear-closeup.jpeg'),
  },
  {
    id: 'w28',
    title: 'Tailoring — Steady Medium',
    category: 'Fashion',
    type: 'video',
    aspect: 'aspect-[9/16]',
    src: m('menswear-tailoring.mp4'),
  },
  {
    id: 'w23',
    title: 'Barefoot — Scene Direction',
    category: 'Fashion',
    type: 'video',
    aspect: 'aspect-[9/16]',
    src: m('menswear-barefoot.mp4'),
  },
  {
    id: 'w11',
    title: 'Team Lookbook — Apparel',
    category: 'E-Commerce',
    type: 'image',
    aspect: 'aspect-[16/9]',
    src: m('remove_all_text_2K_202606151141.jpeg'),
  },
  {
    id: 'w12',
    title: 'Natural Glow Headshot',
    category: 'Beauty',
    type: 'image',
    aspect: 'aspect-[4/5]',
    src: m('3408c83c-3d8b-4cc2-880d-845ca42c7779.JPG'),
  },
  {
    id: 'w13',
    title: 'Together — Lifestyle Set',
    category: 'Advertising',
    type: 'image',
    aspect: 'aspect-[9/16]',
    src: m('ebad76c5-4b66-4e79-ba1c-d9177bb9bbd3.JPG'),
  },
  {
    id: 'w24',
    title: 'Calm Presence — Dolly In',
    category: 'Fashion',
    type: 'video',
    aspect: 'aspect-[9/16]',
    src: m('menswear-calm-presence.mp4'),
  },
  {
    id: 'w29',
    title: 'Lounge — Over the Shoulder',
    category: 'Fashion',
    type: 'image',
    aspect: 'aspect-[9/16]',
    src: m('menswear-over-shoulder.jpeg'),
  },
  {
    id: 'w30',
    title: 'Tight Crop — Portrait',
    category: 'Fashion',
    type: 'image',
    aspect: 'aspect-[9/16]',
    src: m('menswear-tight-crop.jpeg'),
  },
  {
    id: 'w25',
    title: 'Open Shirt — Push & Tilt',
    category: 'Fashion',
    type: 'video',
    aspect: 'aspect-[9/16]',
    src: m('menswear-open-shirt.mp4'),
  },
  {
    id: 'w14',
    title: 'Duo — Product Feature',
    category: 'Advertising',
    type: 'image',
    aspect: 'aspect-[9/16]',
    src: m('the_exact_same_two_girls_202605051524.jpeg'),
  },
  {
    id: 'w15',
    title: 'Physique — Retouch & Restore',
    category: 'Restoration',
    type: 'image',
    aspect: 'aspect-[16/9]',
    src: m('freepik__tile-1__16375.jpeg'),
  },
  {
    id: 'w16',
    title: 'On-Pack — Food Promo',
    category: 'Food & Beverage',
    type: 'image',
    aspect: 'aspect-[9/16]',
    src: m('9b43a469-c0f2-436e-b1e8-11a31dd0a43e.JPG'),
  },
  {
    id: 'w17',
    title: 'Family Living — Lifestyle',
    category: 'Advertising',
    type: 'image',
    aspect: 'aspect-[9/16]',
    src: m('3b35c68c-e266-4b37-8e87-31fc93b00f46.JPG'),
  },
]

/** Three standout pieces used in the hero collage. */
export const heroTiles: { tag: string; type: 'image' | 'video'; src: string }[] = [
  {
    tag: 'Beauty · Still',
    type: 'image',
    src: m('04afa4de-9b0c-4e30-97c8-f1f1f5fee9b6.JPG'),
  },
  {
    tag: 'Fashion · Video',
    type: 'video',
    src: m('doc_2026-06-15_13-45-51.mp4'),
  },
  {
    tag: '',
    type: 'image',
    src: m('A_premium_4K_vertical_9_16_202605051519 (2).jpeg'),
  },
]
